-- phpMyAdmin SQL Dump
-- version 4.9.4
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Jun 11, 2020 at 09:46 PM
-- Server version: 10.3.23-MariaDB-log-cll-lve
-- PHP Version: 7.3.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `lankparb_tours`
--

-- --------------------------------------------------------

--
-- Table structure for table `hotel_ratings`
--

CREATE TABLE `hotel_ratings` (
  `id_hotel_ratings` int(11) NOT NULL,
  `hotel_name` varchar(100) NOT NULL,
  `rating` double NOT NULL,
  `total_rating` double NOT NULL,
  `raters` int(11) NOT NULL,
  `lat` double DEFAULT NULL,
  `lng` double DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `hotel_ratings`
--

INSERT INTO `hotel_ratings` (`id_hotel_ratings`, `hotel_name`, `rating`, `total_rating`, `raters`, `lat`, `lng`) VALUES
(1, 'Rock Side Hotel', 4.3, 26, 6, 7.2043302, 80.1733352),
(2, 'La Olives Hotel', 3.7, 48, 13, 7.2036358, 80.1722885),
(3, 'Hotel De Amana', 4.2, 21, 5, 7.1829229, 80.1484469),
(4, 'Samera Hotel', 3.4, 34, 10, 7.6009883, 80.2610498);

-- --------------------------------------------------------

--
-- Table structure for table `package`
--

CREATE TABLE `package` (
  `package_id` int(11) NOT NULL,
  `name` varchar(300) CHARACTER SET latin1 DEFAULT NULL,
  `rate` double DEFAULT NULL,
  `tour_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `package`
--

INSERT INTO `package` (`package_id`, `name`, `rate`, `tour_id`) VALUES
(1, 'AIRPORT > KANDY > BENTOTA > AIRPORT VIA COLOMBO', NULL, 1),
(2, 'AIRPORT > KANDY > NUWARAELIYA > BENTOTA > AIRPORT VIA COLOMBO', NULL, 2),
(3, 'AIRPORT > SIGIRIYA > KANDY > Ella > BENTOTA > AIRPORT VIA COLOMBO', NULL, 3),
(4, 'AIRPORT > SIGIRIYA > KANDY > Ella VIA NUWARAELIYA > BENTOTA > AIRPORT', NULL, 3),
(5, 'AIRPORT > KANDY > NUWARAELIYA > YALE > MIRISSA > AIRPORT VIA COLOMBO', NULL, 3),
(6, 'AIRPORT > NEGAMBO > KANDY > NUWARAELIYA > BENTOTA > AHUNGALLA > AIRPORT VIA COLOMBO', NULL, 4),
(7, 'AIRPORT > COLOMBO > KANDY > NUWARAELIYA > ELLA > BENTOTA > AIRPORT', NULL, 4),
(8, 'AIRPORT > KANDY > NUWARAELIYA > Ella > Bentota > AIRPORT VIA COLOMBO', NULL, 5),
(9, 'AIRPORT > ANURADHAPURA > SIGIRIYA > POLONNARUWA > KANDY > NUWARAELIYA > MIRISSA > AIRPORT VIA COLOMBO', NULL, 5),
(10, 'AIRPORT > SIGIRIYA > POLONNARUWA > KANDY > NUWARAELIYA > ELLA > BENTOTA > NEGAMBO > AIRPORT', NULL, 6);

-- --------------------------------------------------------

--
-- Table structure for table `testimonial`
--

CREATE TABLE `testimonial` (
  `id_testimonial` int(11) NOT NULL,
  `review` text CHARACTER SET latin1 DEFAULT NULL,
  `name` varchar(200) CHARACTER SET latin1 DEFAULT NULL,
  `date` varchar(45) CHARACTER SET latin1 DEFAULT NULL,
  `lang` varchar(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `testimonial`
--

INSERT INTO `testimonial` (`id_testimonial`, `review`, `name`, `date`, `lang`) VALUES
(1, 'Seit 2011 begleitet mich Harsha bei meinen Reisen über Sri Lanka und hat auch großen Anteil an der Entstehung meiner Bildbände, da er mein Interesse am Fotografieren teilt.\r\nIch schätze seine freundliche Art, seine HIlfsbereitschaft und nicht zuletzt seinen Humor. Eigentlich kann ich mir eine Sri Lanka-Reise ohne sein Beisein nicht mehr vorstellen.', 'Christine', '27.7.2014', 'du'),
(2, 'Harsha ist der beste Fahrer und Führer, den wir bis jetzt in Asien kennengelernt haben! Insbesondere für Familien mit Kindern ist er wärmstens zu empfehlen! Er versucht allen, ihre Wünsche zu erfüllen!', 'Andrea', '29.7.2014', 'du'),
(3, 'Wir waren 18 Tage mit Harsha unterwegs und er hat uns wirklich jeden Wunsch erfüllt. Er hat tolle Ideen und Tipps und kennt die Insel wie seine Westentasche.', 'Johannes', '1.8.2014', 'du'),
(4, 'Harsha hat unsere Flitterwochen in Sri Lanka zu einem unvergesslichen Erlebnis gemacht, da er nicht nur die tollsten Ecken der Insel kennt, sondern auch viel über Land und Leute erzählen kann. Er hält sich gerne dezent im Hintergrund, steht aber gleichzeitig für alle Unternehmungen und Wünsche zur Verfügung. Einfach spitze!', 'Anne', '4.8.2014', 'du'),
(5, 'und hier:\r\n\r\nHarsha ist einfach fabelhaft. Er hat uns Land und Leute mit viel Humor und Echtheit näher gebracht und uns sehr viel über die Kultur erzählen können. Danke Harsha, dass du uns zum Fischen mitgenommen hast! Es war für uns ein einzigartiges Erlebnis!! Wir kommen sicher wieder!! Bis bald auf Facebook :-)', 'Petra', '20.8.2014', 'du'),
(6, 'Wir waren von Mitte August bis Anfang September drei Wochen unterwegs, zuerst mit Harsha´s Vater und ab der Halbzeit mit Harsha selbst. Er war ein sehr aufmerksamer Begleiter und zuverlässiger Fahrer, der immer präsent, aber nie aufdringlich war! Seine humorvolle Art und seine Kenntnis des Landes haben unseren Urlaub extrem bereichert. Wir haben die Zeit, die viel zu schnell vergangen ist, sehr genossen. Vielen Dank, Harsha!!!\r\n\r\n', 'Stefan, Petra und Sophie', '2.10.2014', 'du'),
(7, 'Wir haben eine Turbo Tour mit Harsha hingelegt. Wir hatten leider insgesamt nur 5 Tage auf Sri Lanka, die wir gerne mit einem Fahrer begleitet durchführen lassen wollten. Nach einigen Recherchen im Internet sind wir auf Harsha gestoßen. Im Nachhinein können wir sagen, dass alles perfekt lief! Wir wurden von Harsha am Flughafen abgeholt, er war so flexibel, dass wir Ort noch unsere Planung umschmeißen konnten und er alle Gästehäuser organisierte. Was wir mochten war, dass Harsha uns alle Infos zu den jeweiligen Statuen / Plätzen gegeben hat, wir aber alleine die Plätze erkunden durften. Alles in allem, war es eine perfekte Reise mit einem super Guide! Vielen Dank an Dich.', 'Christopher und Jenny', '11.12.2014', 'du'),
(8, 'Vom 08. - 12.12.2014 waren wir mit Harsha auf einer 5-tägigen Tour unterwegs. Wir haben ihn als sehr aufmerksamen, humorvollen, hilfsbereiten und äusserst zuverlässigen Menschen kennen gelernt. Sein Fahrstil war so was von angenehm; so konnten wir völlig entspannt die zum Teil längeren Fahrten geniessen. Was uns total beeindruckt hat, ist die Tatsache, dass er sich wirklich an Dinge erinnert und diese auch umgesetzt hat, die man mal zu Beginn der Reise im Gespräch erwähnt hatte. Diese Art von Aufmerksamt freute uns sehr! Ebenso hat er ein geschultes Auge für so manches Detail. Dank Harsha haben wir echte Einblicke zu Land & Leuten Sri Lankas erhalten. Unser Dank & Respekt gilt Harsha.', 'Silvia und Susanne', '12.2.2015', 'du'),
(9, 'Wir sind zwar nicht mit harsha selbst gefahre, aber er hat uns den driver organisiert und dieser war sehr verlässlich und freundlich.Es hat alles reibungslos wie besprochen funktioniert.', 'Julia und Christian', '3.4.2015', 'du'),
(10, 'Wir waren im Juni 2015 in Sri Lanka. zuerst buchten wir Harsha für 3 Tage. Es war so toll, dass er gleich für weitere 2 Tage herhalten musste :) nach diesen insgesamt 5 Tagen hatten wir alle 4 einen Freund mehr. Danke Harsha für die unvergesslichen Tage, und vor allem Nächte! Dass wir so tief in die Kultur blicken konnten, hätten wir uns nicht im Traum denken können!! Empfehlenswert Ende nie!!!!!', 'Chris, Susi, Mara und Milo', '31.8.2015', 'du'),
(11, 'Harsha hat uns Juli/August 2015 14 Tage lang sein Land gezeigto - unvergessliche Tage! Harsha hat uns viel über die Kultur und sein Land erzählt. Wir haben spontan das Programm immer wieder angepasst - er hat uns an Orte geführt, welche wir von uns aus nie besucht hätten - danke Harsha! Er ist ein sehr umsichtiger und angenehmer Fahrer. Die Abende, welche wir mit ihm zusammen verbracht haben, haben wir SEHR genossen! Merci für alles!! doris, renzo, selina, tabea', 'Doris', '4.9.2015', 'du'),
(12, 'Wir waren im Februar 2016 in Sri Lanka. Durch meine Freundin hatten wir das große Glück Harsha kennzulernnen. Er hat für uns eine ganz tolle Tour organisiert. Wir hatten sehr viel Freude und Spaß miteinander. Er ist ein ganz toller Mensch und sehr liebenswert. Wir kommen wieder!', 'Kathi', '6.3.2016', 'du'),
(13, 'Hallo Frau Peinsteiner,\r\n\r\nich möchte Ihnen kurz von unserer Reise nach Sri Lanka berichten. \r\nDurch Ihre Homepage haben wir im Vorfeld sehr viel über das Land erfahren und so auch Harsha gefunden. \r\nUns hat die 5-Tages-Tour mit Harsha sehr gut gefallen, er war so bemüht uns immer das Richtige zu zeigen, es hat alles super gepasst. \r\nDie Tour war allerdings viel zu kurz, uns würde auch der Norden der Insel reizen, Harsha hat uns einiges davon erzählt. \r\nSie haben einen sehr netten “Sohn” auf Sri Lanka und ich hoffe, er kann sich seinen Wunsch erfüllen und heuer nach Österreich kommen. \r\nWir würden uns über einen Besuch von Harsha und Ihnen sehr freuen.', 'Brigtte an Christine Peinsteiner', '7.4.2016', 'du'),
(14, 'Hi Harsha\r\n\r\nHow are you? We hope that you are fine?\r\n\r\nWe are now back in Germany.\r\nWe want to thank you for this wonderful week in Sri Lanka.\r\nIt was such a nice trip/ holiday with you.\r\nEverything was so great and we loved it.\r\n\r\nHope we stay in touch\r\nBest wishes\r\nJulia, Niels, Jasmin and Kai', 'Julia, Niels, Jasmin and Kai', '25.7.2016', 'en'),
(15, 'Wir machten im Juli  eine 17-tägige Rundreise durch Sri Lanka. Harsha hat diesen Urlaub zu einem ganz besonderen Erlebnis gemacht. Er zeigte uns spannende Orte abseits der Touristenpfade und ermöglichte uns einen Einblick in die Kultur Sri Lankas. Sein Motto „Come as a tourist and leave as a friend!“ trifft bei uns auf jeden Fall zu!', 'Florian und Katrin', '5.8.2016', 'du'),
(16, 'Leider waren wir nicht mit Harsha persönlich unterwegs, was wir bedauern, weil wir sehr viel Gutes gelesen haben. Harsha hat aber einen anderen Fahrer Eranga für uns organisiert, der uns bereits vom Flughafen abgeholt hat und es hat alles wie am Schnürchen funktioniert.Das Menschlich ist besonders hervorzuheben, Eranga war wie ein Freund zu uns, bestieg jeden Berg mit uns und zeigte uns so viele einheimische Lokale sodass wir Sri Lanka mit allen Sinnen erleben konnten.Danke an Harsha für die Organisation', 'Christine und Heinz', '11.8.2016', 'du'),
(17, 'Was personally recommended Harsha\'s services via a friend - great choice. We made up our own itinerary or I am sure he would arrange this too. We were picked up in Kandy, our choice, as we wanted to take the train from Colombo to Kandy. We then drove up to the Sigiriya area and then back down to Kandy and up to the Highlands before being dropped off at the airport in perfect time for our flight - 6 days. Harsha was an excellent tour guide, courteous and considerate to our needs, suggesting activities as appropriate and accommodating our suggestions and preferences too - very flexible. The vehicle was a \'combi\' type, which very clean and comfortable. Harsha was a careful driver, not easy when navigating the many lorries and tuk-tuks! Harsha was always on time and would change meeting times etc without hesitation, and always a lovely smile. We felt as though we were travelling with a friend, who was keen to show us all his lovely country had to offer. Not one of the big operators, but if you want a highly personalised, flexible, friendly approach, then this family tour business is for you.', 'Njw', 'Feb 3, 2018', 'en'),
(18, 'Meine Freundin und ich waren im Februar/März 2017 für zwei Wochen in Sri Lanka.\r\nDie ersten 5 Tage machte wir mit Harsha (Lanka Tour Driver) eine wunderbare Rundreise.\r\n\r\nHarsha zeigte uns dabei viele wunderschöne Plätze seines Landes und begleitete uns zu den verschiedenen Sehenswürdigkeiten. So konnten wir die vielen Natur- und Kulturwunder der Insel hautnah erleben. Unsere Reise führte uns nach Sigirya, Dambulla, Kandy, Haputale, Ella, Nuwara Eliya, Yala Nationalpark, Galle und an der Küste entlang zum gebuchten Hotel (Shinagawa Beach) für unseren Badeurlaub. Wir bekamen tolle Eindrücke und sahen die verschiedenen Bräuche und Zeremonien aus nächster Nähe. \r\n\r\nGerne möchten wir irgendwann den Norden und den östlichen Teil der paradisischen Insel besuchen\r\n\r\nZusammenfassend kann man sagen, dass Sri Lanka ein ideales Reiseziel für all jene ist, die eine Kombination aus Natur-, Kultur- und Badeurlaub suchen. Auch die kulinarischen Köstlichkeiten dürfen nicht vergessen werden!\r\n\r\nEin herliches Dankeschön an Harsha für seine Bemühungen!\r\n\r\nElisabeth und Dominik', 'Dominik-Elisabeth', 'Feb 19, 2018', 'du'),
(19, 'We die a 7 das tour with Harsha. We visited our favorite sights. Everything worked well. Acommonations were very simple. A good trip.', 'mundm', 'Feb 19, 2018', 'du'),
(20, 'We really enjoyed the trip with Harsha! We highly recommend him as a tour guide as he was really kind and helpful in any situation! We enjoyed the time with him and rather saw him as a friend than as a tour driver. You are always able to laugh with him and simply have a good time! Our trip only has been two days, but during those days we explored a lot (elephant riding, rafting, a typical Indian dinner etc.) and Harsha always adjusted to our needs and stopped everywhere we wanted to go. I can only recommend this business if you want to experience the insider tips of visiting Sri Lanka! Since its a small operating business Harsha really puts a lot of effort in ever trip and can really adjust to your needs.', 'Caroline S', 'Feb 19, 2018', 'en'),
(21, 'Ich war im Oktober 2016 für 9 Tage mit Harsha unterwegs und es war eine beeindruckende Tour! Es hat alles bestens geklappt, von der Kontaktaufnahme und der Planung der Route per Mail bis zum Service vor Ort war alles top. Da ich alleine verreist bin und möglichst viel von der Insel auch abseits der Touristenpfade erkunden wollte, hab ich mich für die Tour mit Harsha entschieden und es keine Sekunde bereut. Er war sehr flexibel, ist auf meine Wünsche eingegangen auch abgelegenere Orte zu besichtigen und auch die von ihm empfohlenen Unterkünfte waren alle sehr empfehlenswert.\r\nIch kann Harsha als Tourguide nur wärmstens empfehlen, da man sich wirklich gut aufgehoben fühlt und auch das Preis-Leistungsverhältnis ist auf jeden Fall top!', 'evak', 'Feb 22, 2018', 'du'),
(22, 'At the beginning of may we planned our trip to Sri Lanka. We went with our two best friends. In Sri Lanka we’ve met Harisha, our tour guide. What we wanted to do was very stipped out. Harsha had great tips of places to expand the trip. Thanks to Harisha our vacation was better than expected. Sri Lanka was fantastic and amazing. We are so grateful we’ve could explore Sri Lanka the way we had. Meeting new people and soaked in the culture of Sri Lanka. \r\nIn two weeks we had done a lot of things like visiting the big boda in Kandy, a lot of waterfalls, meeting the local people. And not to forget we ate a lot of curry’s. Last stop was Pegion Island. Harsha arranged a luxury hotel for us so we could relax. \r\n\r\nHar, our tour guide, thank you so much for you did. Thanks to you we could explore more of beautiful Sri Lanka. \r\n\r\nMay we meet again!!\r\n\r\nLots of Love,\r\n\r\nDoris & Bart (From Holland)\r\nHein & May (From USA)', 'Doris, Bart, Hein & May', 'Feb 22, 2018', 'en'),
(23, 'In unseren 3 Wochen in Sri Lanka war Harsha unser Mann für alle Fälle. Fahrer, Guide, Reiseleitung, Organisator, Gitarrenspieler, Koch, uvm... je nach unseren wünschen :)\r\nWir waren immer gut aufgehoben in seiner Obhut. Seine sympatische und unterstützende Art machte unsere gemeinsame Reise sehr angenehm. Nicht nur das wir spitzen Empfehlungen für Reiseziele von Ihm bekamen, gerne übernimmt er auch die Buchung von Unterkünften. \r\nAuch wenn der Verkehr in Sri Lanka für uns anfangs gewöhnungsbedürftig war, sorgte Harsha\'s entspannter und vorausschauender Fahrstil dafür, dass wir uns stets sicher fühlten.\r\nHarsha spricht sehr gutes Englisch, weshalb die Verständigung immer super klappte.\r\n\r\nWenn wir Sri Lanka erneut bereisen, dann am liebsten mit Ihm!', 'michaelanderl', 'Mar 12, 2018', 'du'),
(24, 'Wir waren rund 7 Tage mit Eranga Eroshan (Era) quer durch Sri Lanka unterwegs. Es war echt soooo toll. Er war jeden Tag pünkltich! Hat uns Sachen gezeigt, wo ich mir sicher bin, dass das \"normale\" Touristen nie zu sehen bekommen. Abgelgene Teeplantage, Regenwald, Dschungel, Schwimmen und Essen mitten in einem Fluss! Echt ein Traum, wenn man nicht den normalen Touristenstrom folgen will und auch etwas abenteuerlustig ist. Wir haben uns um fast nichts kümmern müssen. Er hat uns immer gefragt, wollt ihr das machen, wollt ihr das sehen. Da gibt\'s noch was zu sehen. Echt toll. \r\nUnd was natürlich noch war, wir hatten unheimlich viel Spaß miteinander. \"Era\" ist ein lebensfroher, lustiger Mensch. \r\n\r\nAlles in allem ein absolut genialer Urlaub mit einem tollen Fahrer, der dir nicht nur die Schönheit der Insel zeigt, sondern mit dem du wirklich auch in die Kultur und die Lebensweisen der Menschen dort eintauchen kannst!!!', 'Clemente', 'Mar 10, 2018', 'du'),
(25, 'Wir haben im Februar 2018 eine 21-tägige Rundreise mit Kapila durch Sri Lanka gemacht. Kapila spricht einfaches, verständliches Englisch. Zu allen Vereinbarungen erwies er sich als absolut zuverlässig (z. B. immer pünktlich). \r\nUnsere Tour ging von Negombo nach Anuradhapura, Polunaruwa, Sigiriya, Dambulla, Kandy, Dalhousie, Nuwara Eliya, Udawalawe, Tangalle, Galle wieder zurück nach Negombo.\r\nEr ist ein sehr erfahrener Reiseleiter, der nicht nur die gängigen Touristenziele kennt, sondern auch weitere lohnende Ausflugs- und Besichtungsziele vorschlägt. Auf Wünsche unsererseits ist er immer sofort eingegangen. Auch wenn man ein Lunch essen möchte, einen Fruchtsaft trinken möchte oder einen weiteren interessanten Tempel sehen möchte, weiß er immer einen guten Ort. Durch ihn haben wir auch das landestypische Essen kennengelernt, das an der Straße verkauft wird. \r\nFast alle Hotels auf der Rundreise hat er für uns gebucht (sie waren im Preis enthalten) und es waren immer gute Hotels, teilweise mit Pool. \r\nBei Sehenswürdigkeiten hat er uns nur dann vorgeschlagen einen Guide zu nehmen, wenn dies auch sinnvoll war (bei vielen Sehenswürdigkeiten braucht man keinen Guide). Nie wurden wir dazu gedrängt, irgendwelche Souvenirshops zu besuchen und etwas zu kaufen.\r\nKapila gibt auch Erläuterungen zu Flora und Fauna, Landwirtschaft, Besonderheiten auf dem Weg sowie zur Kultur Sri Lankas.\r\nWir empfehlen Kapila als kompetenten Reiseleiter für ganz Sri Lanka!\r\nVielen Dank, Kapila, für diese erlebnisreiche Rundreise in stets guter Atmosphäre!\r\nBirgit und Peter Sellmer, Berlin', 'Birgit', 'Mar 16, 2018', 'du'),
(26, 'Harsha and his familiy were the best guides ever!!! Kids-sitting included! ;-) Great trip with great people! Thank you Harsha!', 'andreasteiner', 'Apr 16, 2018', 'en'),
(27, 'Harsha Bandara (+94 777732529) drove me and my family in his minivan from Apr 26 to May 02, 2018 as we covered Colombo, Sigiriya, Dambulla, Kandy and Negombo. Firstly, he gave us a great rate which was 30% lesser than whatever else decent quote we got and then lived up to what he promised. We found him prompt, reliable, caring and safe driver who was genuinely eager to give you a good time and made appropriate recommendations when asked for without trying to be an agent or middle man working for his side cut. We would happily tour again with him on our next trip.', 'AnandaSanjeev', 'May 7, 2018', 'en'),
(28, 'Harsha is an excellent driver. He knows where to go at the right times, what roads to take and not take for efficient timing; he is very honest, knowledgeable, funny, and fun to be around. He also has a very good eye for spotting interesting things (ie. elephants, birds, etc., ...). You won’t go wrong with him as your driver. His prices are very comparable. You also do not need too worry so much about special details, let’s say, if you are planning a safari or going to ancient sites, for he has the connections; he planned our trip to Sigiriya and Minneriya National park (safari driver/guide). Also—which was really nice—Harsha has a very comfortable car with a good working air-conditioner. \r\nThanks Harsha, we had a very good time, especially meeting some of your family and eating all the fresh fruits from the garden (mangos, rose apples, star fruit, etc.).', 'Darren c', 'Jun 4, 2018', 'en'),
(29, 'We were so pleased with our private tour driver Harsha Bandara on our recent 5-day tour around Sri Lanka. Harsha was flexible and accommodating from start to finish. Before arriving in Sri Lanka, we weren’t sure whether to just have him take us from the airport to our hotel in the Eastern Province, or whether to have a driver for our whole trip. After meeting him at the airport and beginning to chat we knew we would enjoy his company and benefit greatly from his inside knowledge of the country, and we are so glad we decided to have him as a personal driver for our whole trip! \r\nHarsha was never demanding in anyway, and was always courteous, putting our needs first. He was very pleasant company (with such a light-hearted demeanour!) chatting as we initiated and never making us feel as if we needed to talk (which was the perfect environment for long 6 hour drives!). He spotted some elephants, toucans, lizards and monkeys for us along the way, and always answered our many questions about what we were seeing as we drove. He was always ready to go when we were, and was willing to travel at anytime of the day/night (did not complain about late evening travels). \r\nThe car was also very comfortable and comes with free wifi and free water bottles. We felt very safe with him and it made for a hassle-free, concern-free way to see the country. He can make helpful suggestions for things to do and hotels to stay at but never even tries to persuade you to do something you are not interested in doing. \r\nYou have nothing to worry about with Harsha. Best tour driver we could have asked for!', 'eandd', 'Jun 8, 2018', 'en'),
(30, 'We travelled with Harsha for three times now since 2013.. But we selected him as our driver for the whole period of travelling in the first meet.. he is that much friendly and protective.. he is very polite when working with us.. and he treated very well to little ones.. he shows us the real srilanka even some srilankans haven\'t still seen .. so we re very lucky to travell with a person like him.. he is very clever in explation of the things and places.. birdwatching and nimal watching safaris.. night campaigns bbq parties are the unforgettable things in our trip with him.. and the special thing is he offers us ao many sweet food and fruits.. even his family is also ver good .. he comes with the clean vehicle on time without any hesitataing at anytime without conciderng about day or night.... he is the best driver I\'ve ever met when travelling around the world.. so I recommend him without any doubt to the other travellers.. he is the best tourist driver /best personal driver / best guide in srilanka I\'ve ever seen..', 'davina fernandz', 'Jun 11, 2018', 'en'),
(31, 'Lanka tour driver travell company can be recommend as the best travel company in Srilanka.. We used to travell with Harsha in last month. . He shows us whole srilanka even we haven\'t heard about.. When we write him our 1st email, he explain us everything and answer all the questions through quick mails.. He is the one who arranged clean and clear comfortable accommodations to the best rate.. He told it us and did as he said. He is like a gps service and know all the little roads to all the places .. He is very kind, pleasant, and on time.. His free wifi service in the vehicle is also shoukd be appreciated.. His home made food is really amazing.. I recommend Harsha to everyone who hope to visit srilanka.. He is the one who gave us a chance to have the best trip in our whole life time. He is the beat tour guide and the best personal driver in Srilanka who offers a safe travell for his all clients.. Thank you Harsha.. Lets meet again.', 'chritine', 'Jun 11, 2018', 'en'),
(32, 'Having just returned from a 14 day\'s private tour in Sri Lanka I couldn’t not put fingers to the keyboard to express our appreciation and gratitude for the friendship, professionalism, knowledge and advice shared with and from Lanka tour driver Harsha . Harsha was the consummate professional from our very first meeting at the Galle Face Hotel in Colombo until the final emotional handshake at the Bandaranaike International Airport.\r\n\r\nEverything in between went absolutely to clock work and there was nothing that Harsha couldn’t arrange on behalf of anyone of our group of 04 friends travelling as one, and I mean nothing! From recommending and fast tracking entry tickets to popular tourist attractions, passionately sharing his country’s deep and rich culture and history, meticulously navigating Sri Lanka’s challenging traffic behaviours to a cold refreshment at the end of the day. He could do it all and not only with a smile but an infectious laugh that I will hold forever. And Lankatourdriver is the best gps service in srilanka I\'ve ever seen because there was nothing he saw as a challenge while driving..\r\n\r\nLanka tour driver must be Sri Lanka’s most sought after and number 1 guide and if not I’m sure he soon will be.\r\nBest luck Lanka tour driver', 'Derick', 'Jul 20, 2018', 'en'),
(33, 'We are a couple in the age of 28 and 34 and booked a 5 days journey in december 2017 with Kapila.\r\nSincerlly out plane was 7 hours to late, but for Kapila this was no problem.\r\nHe is a smart and very friendly gentleman from sri lanka. We spend a lot of time in this 5 days together and listened with big ears to his stories about the country.\r\nWe loved to travel around with him.\r\nEvery hotel was nice. In the booking phase we communicated via mail togehter and had the opportunity to join each hotel what we want.\r\nDuring the trip it was always possible to make a stop whereevver we want.\r\nOn this way we had a really really good time together.\r\nSo we can recommend Kapila to everybody who wants to see the country on a personaly and ftiendly way.\r\nThe price of Kapila is totally ok, because you will see that the country is in some things not the cheappest. \r\nWe would book hin every time again when we will come again to Sri Lanka.\r\nAh and we forgot to say you can join the points if interest up to you. Nothing is fixed, so you can create the trip up to you.\r\nBest regards\r\nLana & Gerald', 'GeraldSeil', 'Jul 28, 2018', 'en'),
(34, 'Contacté con kapila por internét para hacer un tour con mis hijos por Sri Lanka.Conozco prácticamente todo Asia y el recuerdo que tengo de éste viaje es maravilloso tanto por el país como por la profesionalidad y seriedad de Kapila que nos acompañó y llevó por esas carreteras durante todo el recorrido controlando todo a la perfección y por supuesto sin poner ningún impedimento al decirle que iba en silla de ruedas ,al contrario siempre dispuesto a ayudar .Al final del viaje le pagué lo acordado y el precio por el servicio recibido fué muy muy barato.', 'antonio m', 'Jul 28, 2018', 'du'),
(35, 'We go from Hikaduwa over Kandy to Colombo. Kapila show us all the places of interest, and especially we got a glimpse of the life of the locals by visiting his family and friends. I can everybody recommand to book a round trip with Kapila Bandara.', 'othmar conny', 'Jul 28, 2018', 'en'),
(36, 'Within our srilankan trip we had great experiences with our personal driver Harsha.. his comfortable clean and clear vehicle should be appreciated... there was a tv and a free wifi service in his car.. with a good space which we can travel comfortably.. he is very honest.. we never forget his honest smile... he did everything as he said and promised.. we had a nice vacation in srilanka than that we expected.. he is very helpfull and gave us a good support in everywhere during the whole trip..\r\n(Our best driver Harsha) was always right on time (bit early) and we always felt safe during chaotic traffic. And acting like a gps servive.. he is wellknown with all most all roads in srilanka.. his friendly service made us more comfortable in everywhere.. He made sure we didn\'t pay to much, showed us good local restaurants with real lankan taste.. specialy in Ella.. and organised safari\'s...\r\nAnd at all the time he didnt forget to help us in saving money without wasting much.. he help us to use every moment in a usefull manner..\r\nHis family also very kind and friendly.. he provide us a free meal with lankan taste and hjs mother prepared it and still we can remember the taste.. he used to do an hiking with us.. and his free water massage and free water during the whole tour should be appreciated.. their pets ( cats and dogs).. tikky, tave,shelly ,sinky,rex and jimmy are very adorable and still we miss them.. we have all the memories as photos that we took during our trip.. he is also a best photographer...\r\nHe promised us to give an awesone train ride and did as he said.. his night campaing was the best.. Even after 10 days journey with him we still in contact with him.. and he still always find about us.. we sharing our ideas even right now.. he is that much friendly.. and always giving the most reasonable quotes than that of other drivers in srilanka.. as his service is much valuble than his quote.. this is the ever best trip we had.. we saw a lot within our tour.. he is the best personal driver in srilanka.. We highly recommend him without any hesitation..!..\r\nHe is the best tourist driver.. he is the ever best one..', 'Rolfsteve', 'Jul 29, 2018', 'en'),
(37, 'We used to travel with Harsha and had great fun..it was the unforgettable trip..\r\nHe shows us the real srilanka.he was not just a driver...\r\nA singer,guitar player,photographer,gps service, a good friend, a compact of everything.. he is the best srilankan tourist driver .. excellent driver .. excellent service.. best quotes .. reasonable prices.. \r\nA comfortable vehicle with AC.,WiFi and everything.. best luck harsha. You are the best driver in srilanka..', 'George Peter', 'Jul 29, 2018', 'en'),
(38, 'Sri Lanka - was für ein traumhaftes Land - würde sagen die beste Zeit! Unterwegs mit meinen Fahrer Kapila Bandara - die Route teils von ihm vorgegeben und von mir abgeändert – bei den Unterkünften würde/habe ich persönlich ab 4 Sterne wählen/gewählt! Hab auch in der Rice Villa Polonaruwa gewohnt? Lage ein Traum – wunderschön - mitten in den Reisfeldern - da kann man die Seele baumeln lassen! Essen lecker, lecker! Kann ich nur empfehlen!\r\nWann immer ich eine Idee oder Frage hatte - kein Problem es wurde alles realisiert. Während meiner 3 wöchigen Tour - (Kapila fuhr sehr vorsichtig…denn die öffentlichen Busfahrer sind ja unterwegs wie die Henker) machten wir Stopps bei wunderschönen, atemberaubenden Spots – die Gewürzgärten bei Matale würde ich meiden, denn es ist eine reine Abzocke! Abgesehen von all den Sehenswürdigkeiten gefiel mir persönlich: Brief Garden; Markttage in Tangalle; der Besuch in den 2 Waisenhäusern Kandy und Tangalle; der Königliche Botanische Garten Peradeniya bei Kandy; Teeplantagen und Lake Gregory (Nuwara Eliya); Hideaway Lodge oder Lagoon Paradise Beach Resort in Tangalle; Galle Fort¸ OZO Colombo ON 14 Roof Top Bar & Lounge (traumhafte View); all die freundlichen Einheimischen….\r\nIch kann dieses Unternehmen nur weiterempfehlen!!\r\nVielen herzlichen Dank lieber Kapila für die tolle Reise !!!', 'anonymous', 'Jul 29, 2018', 'du'),
(39, 'Wir waren im Mai 2016 zwei Wochen auf Sri Lanka.\r\nDa wir die Route selbst ausgewählt und die Hotels von Deutschland aus gebucht hatten, war es nicht leicht, einen Fahrer zu finden, der entsprechend flexibel war. Kapila erklärte sich auf unsere Internet-Anfrage sofort bereit, uns zu fahren.\r\nEin Hotel in den Bergen konnten wir wegen starker Überschwemmungen und Erdrutschen nicht anfahren. Kapila suchte für uns eine sehr gute Alternative. \r\nEr telefonierte vor jeder Abfahrt mit Freuden und Behörden, um sicher zu stellen, dass wir durch die heftigen Regenfälle nicht in gefährliche Situationen kommen würden. Sein Fahrstil ist angemessen und sicher. Wir hatten zu keinem Zeitpunkt ein Gefühl der Unsicherheit.\r\nVielen Dank für alles, Kapila!\r\nUnsere nächste Rundreise wird auf jeden Fall über Lanka Tour Driver gebucht.\r\n', 'Ann Reisende', 'Jul 29, 2018', 'du'),
(40, 'Very enjoyable and knowledgeable to be with. Friendly genuine guy and made our holiday great fun.\r\nDefinitely went the extra mile.', 'UnitedKingdom', 'Jul 31, 2018', 'en'),
(41, 'My husband and me have been travelling around Sri Lanka with Kapila as our driver. He has been doing his job as a tourist guide for 26 years and knows perfectly about the interests and needs of western tourists – especially people from Austria, Germany and Switzerland. He makes arrangements on request or advises you for any wishes you have.\r\n\r\nShortly before departing from home we let him know by e-mail, that we would prefer to stay in guesthouses instead of expensive hotels. We never knew where he would bring us for the night but we were never disappointed. The rooms were always simple, clean and reasonable in price. The „Inn on the tree echo resort“ in Sigiriya was definitely our favourite accommodation of all.\r\n\r\nOur absolute highlight of the journey was one Sunday when we went fishing with Kapila and his friends.\r\n\r\nWe would like to thank Kapila once again. We’re going to recommend him whenever possible, to everyone planning a trip to Sri Lanka.', 'henry', 'Aug 5, 2018', 'en'),
(42, 'On a friend\'s recommendation the five of us booked an 11 day tour through Sri Lanka with Kapila Bandara of Srilanka Holiday Tours in March 2016.\r\n\r\nAfter getting a preliminary briefing of what we would like to see and do Kapila not only organised an unforgettable trip for us, considering all our wishes, but also gave us plenty of suggestions as to what to do and where to go before and after our tour.\r\n\r\nAfter the pick up in Negombo Kapila chauffeured us from one wonderful place to the next, safely navigating the van with steady hand through the challenges of Sri Lankan traffic :-)\r\n\r\nHe organised excellent accommodation, additional guides for monasteries and national parks, train rides, the lot. In addition to that he took us to some wonderful places we probably would not have visited without his advise.\r\n\r\nAll of us seasoned individual travellers we enjoyed the comfort of having everything expertly organised by a very accommodating Kapila and felt that we would not have had near a nice trip on our own. \r\n\r\nAnd of course, if you are just looking for value for money - you don\'t have to look any further either! \r\n\r\nWe highly recommmend Kapila\'s services to anyone who wants to have a fantastic Sri Lankan experience.\r\n\r\nThank you for sharing your knowledge, expertise and love for your country with us Kapila.', 'Edi G', 'Aug 7, 2018', 'en'),
(43, 'We used Harsha from Lanka Tour Driver for 15 days using an itinerary we created ourselves. I can\'t thank Harsha enough, he really made our trip, I\'m so glad we chose him, and he gave us a very competitive price compared to the other companies we spoke with.\r\nHe was polite at all times and speaks good English. He was also always on time to pick us up. Most importantly he is a good driver and you instantly feel safe in the car with him. You\'ll appreciate this when driving through towns like Colombo and Kandy with heavy traffic. \r\nHe is very knowledgeable about his country and will answer any questions you have. He will often stop and point out animals or fruit spotted during the journey and he will suggest places to stop and get a good photo. We were lucky enough to see a family of 3 elephants at the side of the road! Thanks to Harsha we got a lovely video and photo of this. \r\nEven though we had an extensive itinery in mind, Harsha was still able show us places to stop during our journey to see things like amazing waterfalls or cultural sites. Places we didn\'t even know about.\r\nYou\'ll obviously be spending a lot of time together in the car but it\'s a very laid back atmosphere and the conversation doesn\'t feel forced. He also has WiFi for the car which is helpful so you can update your Instagram with all the amazing places you\'ve just seen!\r\nHiring a driver takes all the stress out of your trip and saves you so much time by not having to rely on public transport. Getting a driver as good as Harsha made it even more special. I highly recommend him.', 'Steven W', 'Aug 16, 2018', 'en'),
(44, 'Harsha was incredible during my partner\'s and my holiday. Although I was initially unsure about hiring a driver for our trip, I am very pleased we did. \r\n\r\nHarsha was always professional and spoke very good English. He was always on time (if not early!). His driving was excellent and despite the chaotic traffic, and numerous tuk tuks, I always felt safe. His car was very comfortable and the Wi-Fi and air con were an added bonus. Harsha made sure the car was kept clean even though we frequently dragged in lots of sand and dust. \r\n\r\nHe was very good at navigating around the country and always found our accommodation (some of which were known for being difficult to find) with ease. \r\n\r\nDuring our trip he took us to various points of interest on route. Some of these were local attractions which tourists wouldn\'t realise were there and others were beautiful unexpected waterfalls. \r\n\r\nAll-in-all he helped make our trip to Sri Lanka a wonderful, relaxed and easy experience. \r\n\r\nI would strongly recommend him for any travels or holidays around this fantastic country.', 'hannah g', 'Aug 16, 2018', 'en'),
(45, 'We booked our tour with Harsha due to a recommendation of a colleague of mine and we did not get disappointed at all. Everything was perfect starting from the planning of our trip with many great suggestions from Harsha which also included our own wishes to the trip itself. \r\nHe is very friendly, a very safe driver (quite important with the traffic there sometimes) and also flexible for adaptations even during the tour. He takes care very well of his guests and makes sure that you will get the best possible impression of Sri Lanka, not only of the sites but also of the hospitality of the people there including himself.\r\nI can say that this trip was unique and I can recommend Harsha without any doubt for everyone who would like to get to know this beautiful country.', 'Flor Spann', 'Sep 7, 2018', 'en'),
(46, 'Unser Fahrer war Kapila! Er hat uns sicher durch die Straßen von Sri Lanka chauffiert und uns viele nützliche Informationen gegeben. Dabei hat er sich an unseren Wünschen und Zeitvorstellungen orientiert, so dass wir sowohl eine interessante Rundreise hatten als auch kurzfristig an einigen tollen Orten länger bleiben konnten. Gerne wieder mit Kapila!', 'Dieter I', 'Sep 11, 2018', 'du'),
(47, 'We have toured with them twice and thoroughly enjoyed both tours. We left all the organisation up to them including hotels, tours, places to visit etc and they did not disappoint. They were recommended to us by a friend in Kuwait who had also used them a couple of times. My husband and I wanted to be shown about the culture, food and people of Sri Lanka and we certainly did that. Kapila is very knowledgeable on all aspects of the country including plants, history and wildlife and we frequently stopped to look at something that he had noticed at the side of the road. If you are considering touring in Sri Lanka you could not be in safer hands.', 'Caz C', 'Sep 24, 2018', 'en'),
(48, 'Der beste Fahrer den man sich nur wünschen kann. Sehr zuvorkommend, freundlich und professionell. Wir hatten wirklich eine sehr schöne Zeit. Danke', 'Maramic', 'Dec 6, 2018', 'du'),
(49, 'Lanka Tours are great! Kitty organised our tour at very last minute. Professional, efficient and friendly. The ongoing communication was very good and reassuring. \r\nOur driver Chamil was absolutely fantastic. He made our vactation the best. He worked very hard and provided maximum service, managing our time well. He understood our needs and preferences. A professional, experienced and reliable driver. \r\nHuge thanks. \r\nI would 100% recommend.', 'Happytimeskr', 'Jan 1, 2019', 'en'),
(50, 'Harsha was the best driver we could have hoped for to accompany us in our tour of Sri Lanka. Not only is he very at ease on the tricky roads of Sri Lanka, but he is also very resourceful: he knows everything and everyone, and he is very kind and accommodating. He had straight answers to our hesitations and avoided us to make many mistakes. Our tour wouldn’t have been as good without him. No hidden costs, couldn’t recommend more. Thanks Harsha!', 'Romainmob', 'Feb 26, 2019', 'en'),
(51, 'I\'d describe this tour company as reliable, customer focused and professional yet fun!\r\n\r\nI had troubles choosing a tour guide and fixing my itinerary - Kitty was helpful, efficient and made planning my holiday a breeze. :)\r\n\r\nHarsha our driver was polite, accommodative and fun to be with. He made local food stops, brought us to underrated scenic locations that really made this trip one of a kind. our trip was always comfortable, the car was always clean and having wifi was a total bonus!\r\n\r\nOverall, id definitely recommend this tour company for anyone looking for a great memorable experience sri lanka.i hope to come back soon!', 'Engku A', 'Mar 3, 2019', 'en'),
(52, 'Super professional service at a great price. \r\n\r\nOur driver Harsha spoke excellent English and had a very clean and comfortable car. He was super flexible, always on time, and was a great driver (a must with all the crazy bus drivers careening about). He had excellent recommendations for what to do, and went the extra mile, helping us get the best spot on the train to Ella and treating us to a few of his favorite street food snacks along the way. We learned a lot about the country from him and would definitely recommend him to friends!', 'Taz', 'Mar 3, 2019', 'en'),
(53, 'Even though I only had a short time, Kitty arranged a memorable tour of Sigiriya, Polonnaruwa, and Kandy. Harsha was a kind, intelligent, honest and safe driver/guide. Lanka Tour Driver offers tours of different lengths, and builds an itinerary around your interests and budget. I highly recommend.', 'azl build', 'Mar 20, 2019', 'en'),
(54, 'We had a two week trip from Colombo over Kandy, Ella, Trincomalee, Sigirya and back to Colombo. Although the trip was a lttle overshadowed due to the attacks in Colombo where we\'ve been close by, but fortunately not directly affected. \r\n\r\nA lot of feeling safe and being able to enjoy the trip is due to our guide Malith who was always well informed about the situation and gave as good feeling. Thus our experience with Sri Lanka turned quickly in overwhelming hospitality, friendlyness and welcoming.\r\n\r\nMalith is one of the kindest and most decent people we ever met on our journeys. He showed us not only most beautiful temple and sights but gave us also understanding of the culture and - very much apppreciated - always good recommendations for local restaurants and markets.\r\n\r\nHe is a very safe and smooth driver, which is not a little thing to say as traffic is a little bit unconventional for the western mind ;-)\r\n\r\nWe would recommend Malith to everybody looking for a well-informed guide, good driver and even more important a truly good compagnion. We certainly will come back and hopefully we\'ll meet again.', 'Derk S', 'May 5, 2019', 'en'),
(55, 'Wir waren 14 Tage mit Kapila in Sei Lanka unterwegs. Er hat uns alle Ùnterkùnfte gebucht ( waren alles sauber und schón). Kapila ist ein sehr ruhiger angenehmer Mann. Er ist sehr hilfsbereit und hat einen sehr angenehmen Fahrstil, was in Sri Lanka nicht normal ist. Uns hat die Rundreise sehr gut gefallen mit ihm. Wann ich gut weiterempfehlen!! Alles gute an Kapila und seiner Familie.!!', 'lucaaa', 'May 28, 2019', 'du');

-- --------------------------------------------------------

--
-- Table structure for table `tour`
--

CREATE TABLE `tour` (
  `tour_id` int(11) NOT NULL,
  `name` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `image_name` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `tour`
--

INSERT INTO `tour` (`tour_id`, `name`, `image_name`) VALUES
(1, '02 NIGHTS\' 03 DAYS\' TOUR', '1.jpg'),
(2, '03 NIGHTS\' 04 DAYS\' TOUR', '2.jpg'),
(3, '04 NIGHTS’ 05 DAYS’ TOUR', '3.jpg'),
(4, '05 NIGHTS’ 06 DAYS’ TOUR', '4.jpg'),
(5, '06 NIGHTS’ 07 DAYS’ TOUR', '5.jpg'),
(6, '07 NIGHTS’ 08 DAYS’ TOUR', '6.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `trip`
--

CREATE TABLE `trip` (
  `trip_id` int(11) NOT NULL,
  `name` varchar(100) CHARACTER SET latin1 DEFAULT NULL,
  `artical` text CHARACTER SET latin1 DEFAULT NULL,
  `todo` text CHARACTER SET latin1 DEFAULT NULL,
  `package_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `trip`
--

INSERT INTO `trip` (`trip_id`, `name`, `artical`, `todo`, `package_id`) VALUES
(1, '01. AIRPORT TO KANDY', 'KANDY is a cultural city and very famous as a main city in Sri Lanka. And belongs to the central province of Srilanka. And it can be known as a sacred city with the world famous lord Buddha’s sacred tooth relic. It can be also introduced as an ancient kingdom of Srilanka which shows the dignity of the little country.', 'Pinnawala elephant orphanage,Gadaladeniya temple,Embekke Temple,Lankathilaka Temple,Temple of Tooth Relic,Royal Botanical gardens Peradeniya,Temple of Tooth Relic', 1),
(2, '02. KANDY TO BENTOTA', 'BENTOTA is an area with a nice beach view. Turtles in Bentota are very cute than we think and the area surrounded with famous madu river is well famous for boat safaris. And we can see lots of cinnamon gardens while doing that relaxing safety boat safari. Jet Ski, banana boat rides, kite surfs, sea plane tours are actually amazing. Jeffery Bava the world famous architecture\'s beautiful home and home garden make us mute for a while after going to that awesome place. And a main point to say is that the turtle conservation project takes an important place in the area.', 'Tea factory,Water rafting,The architecture house Brief Garden,Turtle hatchery Water,Sports at Bentota', 1),
(3, '03. BENTOTA TO AIRPORT VIA COLOMBO', 'COLOMBO is the main city in Sri Lanka and its crowdie city with lots of people and service suppliers. It belongs to western province of the country. It has become a main touristic point not because of its beauty but because of the services can obtain there.', 'Kelaniya Temple,Galle Face,Old Parliament,Bere Lake,Gangaramaya Temple,Shopping Tour', 1),
(4, '01. Airport to Kandy', 'KANDY is a cultural city and very famous as a main city in Sri Lanka. It belongs to the central province of Sri Lanka. And it can be known as a sacred city with the world famous lord Buddha’s sacred tooth relic. It can be also introduced as an ancient kingdom of Sri Lanka which shows the dignity of little country.', 'Pinnawala elephant orphanage,Evening Cultural dancing show', 2),
(5, '02. Kandy to Nuwaraeliya', 'NUWARAELIYA is situated in the central province of Srilanka. It’s the coldest area in our country. With the hill tops covering by the mist it’s add a heaven beauty to this little country. Flowers in little plants make us blind for a moment. Water falls which are coming from the mountain tops make our minds relax for a while.  Tea plantations runs to the infinity make us so attractive to the area and to the little country. Once it makes us feel the country as a Utopia just with the laughter. Golf ground with green leaves make us so playful with horses. Looking at the sun rise by sitting beside the Horton plains while smoking or eating peanuts is the best thing I like. Looking at the hill tops by staying at the moon plains is just like a heartiest meditation.', 'Ceremony at Temple of tooth around 9am,Kandy lake,Royal botanical garden,Ramboda fall,Tea factory and plantations at Nuwaraeliya,Nuwaraeliya city tour and Gregory lake park', 2),
(6, '03. Nuwaraeliya to Bentota', 'BENTOTA is an area with a nice beach view... Turtles in Bentota are very cute than we think and the area surrounded with famous madu river is well famous for boat safaris…And we can see lots of cinnamon gardens while doing that relaxing safety boat safari. Jet Ski, banana boat rides, kite surfs, sea plane tours are actually amazing… Jeffery Bava the world famous architecture\'s beautiful home and home garden make us mute for a while after going to that awesome place. And a main point to say is that the turtle conservation project takes an important place in the area.', 'Devon fall,Water rafting - Kithulgala,Turtle conservation project', 2),
(7, '04. Bentota to Airport via Colombo', 'COLOMBO is the main city in Sri Lanka and its crowdie city with lots of people and service suppliers. It belongs to western province of the country. It has become a main touristic point not because of its beauty but because of the services can obtain there.', 'Madu river boat safari, Kalani temple,Colombo fort,Old parliament,Galle face,Bere lake,Gangarama temple,Shopping tour', 2),
(8, '01. Airport to Sigiriya', 'SIGIRIYA is an historical city which has a deep historical value. It is situated in the north central province of Sri Lanka. It is not only a rock but also a fortress used to be protective from invaders. It was built by king Kashyapa. There’s a nice and an interesting story also which was written around that place. Once it was nominated as a world\'s heritage.', 'Pinnavala elephant orphanage,Hiking to Sigiriya rock to see the sun setting', 3),
(9, '02. Sigiriya to Kandy', 'KANDY is a cultural city and very famous as a main city in Sri Lanka. It belongs to the central province of Sri Lanka. And it can be known as a sacred city with the world famous lord Buddha’s sacred tooth relic.', 'Dambulla cave temple,Nalanda gedige,Matale Hindu kovil ,Evening cultural dancing show at Kandy,Ceremony at Kandy tooth temple ', 3),
(10, '03. Kandy to Ella ', 'ELLA is very touristic with its own nature with mist and cold, Flowers blossom in the sunshine make the nature very beauty. It is very famous to do hiking and for beautiful accommodations and tasty food.', 'Morning Royal botanical garden in peradeniya,Water falls,Tea factories ,Tea plantations ,Nuwaraeliya city tour (ancient post office, local Market, Gregory Lake and park)', 3),
(11, '04. Ella to Bentota', 'BENTOTA is an area with a nice beach view. And the area surrounded with famous madu river,  It is well famous for water sports , Turtle conservation project takes an important place in the area.', 'Ravana water fall,Buduruwagala temple,Udawalawa elephant orphanage,Galle fort', 3),
(12, '05. Bentota to Airport via Colombo', 'COLOMBO is the main city in Sri Lanka and its crowdie city with lots of people and service suppliers. It belongs to western province of the country. It has become a main touristic point not because of its beauty but because of the services can obtain there.', 'Gangaramaya,Independence square,Galle face,Colombo fort,National museum,Outside visit of Old parliament ', 3),
(13, '01. Airport to Sigiriya', 'SIGIRIYA is an historical city which has a deep historical value. It is situated in the north central province of Srilanka. It is not only a rock but also a fortress used to be protective from invaders...  It was built by king Kashyapa. There’s a nice and an interesting story also which was written around that place. Once it was nominated as a world\'s heritage.', 'Pinnavala elephant orphanage,Hiking to Sigiriya rock to see the sun setting', 4),
(14, '02. Sigiriya to Kandy', 'KANDY is a cultural city and very famous as a main city in Srilanka. And belongs to the central province of Srilanka.And it can be known as a sacred city with the world famous lord Buddha’s sacred tooth relic. \r\n', 'Morning we can do a hiking to Pidurangala rock to see sun rise. (Depends on your wish),Nalanda gedige the center of Srilanka,Marimuttu Amman Hindu Kovil,Evening Kandy city tour and temple of tooth relic', 4),
(15, '03. Kandy to Ella via Nuwaraeliya', 'ELLA is very touristic with its own nature with mist and cold, Flowers blossom in the sunshine make the nature very beauty. It is very famous to do hiking and for beautiful accommodations and tasty food.\r\n', 'Morning botanical garden in Peradeniya,Tea factories,Tea plantations,Water falls,Nuwaraeliya city tour,ancient post office,local market,Gregory Lake and park', 4),
(16, '04. Ella to Bentota', 'BENTOTA is an area with a nice beach view. And the area surrounded with famous madu river, it is well famous for water sports, Turtle conservation project takes an important place in the area.', 'Rathnapura gem mine,Turtle conservative place,Brief garden', 4),
(17, '05. Bentota to Airport', NULL, 'If we have enough time with a late departure. You can do water sports in Bentota river,Boat safari in madu river,turtles hatchery', 4),
(18, '01. Airport to Kandy ', 'KANDY is a cultural city and very famous as a main city in Sri Lanka. It belongs to the central province of Sri Lanka. And it can be known as a sacred city with the world famous lord Buddha’s sacred tooth relic. It can be also introduced as an ancient kingdom of Sri Lanka which shows the dignity of little country.', 'Pinnawala elephant orphanage,Gem museum,Kandy dancing show,Kandy tooth temple ceremony at 6pm,Kandy Lake', 5),
(19, '02. Kandy to Nuwaraeliya ', 'NUWARAELIYA is situated in the central province of Srilanka. It’s the coldest area in our country. With the hill tops covering by the mist it’s add a heaven beauty to this little country. Flowers in little plants make us blind for a moment. Water falls which are coming from the mountain tops make our minds relax for a while.  Tea plantations runs to the infinity make us so attractive to the area and to the little country. Once it makes us feel the country as a Utopia just with the laughter. Golf ground with green leaves make us so playful with horses. Looking at the sun rise by sitting beside the Horton plains while smoking or eating peanuts is the best thing I like. Looking at the hill tops by staying at the moon plains is just like a heartiest meditation.', 'Botanical garden,Ramboda fall,Tea factory & Tea plantations,post office,Nuwaraeliya local market visit', 5),
(20, '03. Nuwaraeliya to Yale ', 'YALA is located in the south eastern region of Sri Lanka and extends over two provinces of Hambantota district of southern province and Monaragala district in Uva province. The entrance to the park is at Palatupana, 12km from Kirinda. The distance from Colombo to the entry point of Palatupana is 305km.', 'Visit Horton Plains @ 5am,Train Ride to Ella,Rawana waterfall', 5),
(21, '04. Yale to Mirissa ', 'MIRISSA is a small town on Sri Lanka’s south coast, is a common stop on traveller’s itineraries. The main attraction of the town itself is the numerous whale watching tours on offer – as it’s one of the best places in the world to spot blue whales.', 'Yale safari,Dondra light house', 5),
(22, '05. Mirissa To Airport via Colombo', 'COLOMBO is the main city in Sri Lanka and its crowdie city with lots of people and service suppliers. It belongs to western province of the country. It has become a main touristic point not because of its beauty but because of the services can obtain there.', 'Walk to whale watching at 5.30am,Madu river boat safari,Turtle conservation project,Colombo city tour & shopping,Bere Lake,Colombo national museum,Gangaramaya temple', 5),
(23, '01. Airport to Negambo', 'NEGOMBO is a popular destination for tourists with its pristine beaches, historic canals, lagoons and other breathtaking views. The Porutota stretch has been known for its mushrooming pubs and restaurants for quite a long time. Since many of the star class hotels are also found along this street local businesses too are having quite a potential with tourists walking in to them almost all the time. Shops selling souvenirs shops, swimming accessories, clothes are also found in addition to the pubs and cafes. In an attempt to find out some of the happening places in town, the Life Online walked in to a few known places to taste some of their signature dishes. We also didn’t forget to visit some of the iconic landmarks in town including the fish market, the lagoons and other sacred places of worship.', 'Stay there for overnight and rest,There for we can start by the early morning on next day,After seeing the fish market\r\n', 6),
(24, '02. Negambo to Kandy ', 'KANDY is a cultural city and very famous as a main city in Sri Lanka. It belongs to the central province of Sri Lanka. And it can be known as a sacred city with the world famous lord Buddha’s sacred tooth relic. It can be also introduced as an ancient kingdom of Sri Lanka which shows the dignity of little country.', 'Pinnawala elephant orphanage,Kandy cultural dancing show,Kandy tooth temple ceremony,Kandy Lake', 6),
(25, '03. Kandy to Nuwaraeliya', 'NUWARAELIYA is situated in the central province of Srilanka. It’s the coldest area in our country. With the hill tops covering by the mist it’s add a heaven beauty to this little country. Flowers in little plants make us blind for a moment. Water falls which are coming from the mountain tops make our minds relax for a while.  Tea plantations runs to the infinity make us so attractive to the area and to the little country. Once it makes us feel the country as a Utopia just with the laughter. Golf ground with green leaves make us so playful with horses. Looking at the sun rise by sitting beside the Horton plains while smoking or eating peanuts is the best thing I like. Looking at the hill tops by staying at the moon plains is just like a heartiest meditation.', 'Botanical garden,Ramboda fall,Tea factory & tea plantation,Nuwaraeliya post office,local market visit', 6),
(26, '04. Nuwaraeliya to Bentota', 'BENTOTA is an area with a nice beach view. Turtles in Bentota are very cute than we think. And the area surrounded with famous madu river is well famous for boat safaris. And we can see lots of cinnamon gardens while doing that relaxing safety boat safari. Jet Ski, banana boat rides, kite surfs, sea plane tours are actually amazing. Jeffery Bava the world-famous architecture\'s beautiful home and home garden make us mute for a while after going to that awesome place. And a main point to say is that the turtle conservation project takes an important place in the area\r\n', 'Visit Horton plains at 5am,Devon waterfall,Kitulgala water rafting', 6),
(27, '05. Bentota', NULL, 'Madu river boat safari,Turtle conservation project,Evening beach relax', 6),
(28, '06. Ahungalla to Airport via Colombo', 'COLOMBO is the main city in Sri Lanka and its crowdie city with lots of people and service suppliers. It belongs to western province of the country. It has become a main touristic point not because of its beauty but because of the services can obtain there.', 'Colombo city tour and shopping,Bere Lake,Colombo national museum,Gangaramaya temple', 6),
(29, '01. Airport to Colombo', 'COLOMBO is the main city in Sri Lanka and its crowdie city with lots of people and service suppliers. It belongs to western province of the country. It has become a main touristic point not because of its beauty but because of the services can obtain there.', 'Gangarama temple,Kelani temple,Galle face,Shopping tours', 7),
(30, '02. Colombo to Kandy', 'KANDY is a cultural city and very famous as a main city in Srilanka. And belongs to the central province of Srilanka. And it can be known as a sacred city with the world famous lord Buddha’s sacred tooth relic. \r\n', 'Pinnawala elephant orphanage,Royal Botanical garden,Tooth temple', 7),
(31, '03. Kandy to Nuwaraeliya ', 'NUWARAELIYA is situated in the central province of Srilanka. It’s the coldest area in our country. With the hill tops covering by the mist it’s add a heaven beauty to this little country. Flowers in little plants make us blind for a moment. Water falls which are coming from the mountain tops make our minds relax for a while.  Tea plantations runs to the infinity make us so attractive to the area and to the little country. Once it makes us feel the country as a Utopia just with the laughter. Golf ground with green leaves make us so playful with horses. Looking at the sun rise by sitting beside the Horton plains while smoking or eating peanuts is the best thing I like. Looking at the hill tops by staying at the moon plains is just like a heartiest meditation.', 'Tea factory,Tea plantation,Ramboda Water fall sight seen', 7),
(32, '04. Nuwaraeliya to Ella by train', 'ELLA is very touristic with its own nature with mist and cold, Flowers blossom in the sunshine make the nature very beauty. It is very famous to do hiking and for beautiful accommodations and tasty food.', 'Little Adam’s peak,Nine arch bridge \r\n', 7),
(33, '05. Ella to Bentota', 'BENTOTA is an area with a nice beach view. Turtles in Bentota are very cute than we think. And the area surrounded with famous madu river is well famous for boat safaris. And we can see lots of cinnamon gardens while doing that relaxing safety boat safari. Jet Ski, banana boat rides, kite surfs, sea plane tours are actually amazing. Jeffery Bava the world famous architecture\'s beautiful home and home garden make us mute for a while after going to that awesome place. And a main point to say is that the turtle conservation project takes an important place in the area.', 'Udawalawa elephant orphanage,Rawana waterfall,Galle fort', 7),
(34, '06. Bentota to Airport', NULL, 'Jeffrey bava\'s home or brief garden,turtle conservation place,water sports', 7),
(35, '01. Airport to Kandy', 'KANDY is a cultural city and very famous as a main city in Sri Lanka. It belongs to the central province of Sri Lanka. And it can be known as a sacred city with the world famous lord Buddha’s sacred tooth relic. It can be also introduced as an ancient kingdom of Sri Lanka which shows the dignity of little country.', 'Pinnawala elephant orphanage,Cultural dancing shows\r\n', 8),
(36, '02. Kandy to Nuwaraeliya', 'NUWARAELIYA is situated in the central province of Srilanka. It’s the coldest area in our country. With the hill tops covering by the mist it’s add a heaven beauty to this little country. Flowers in little plants make us blind for a moment. Water falls which are coming from the mountain tops make our minds relax for a while.  Tea plantations runs to the infinity make us so attractive to the area and to the little country. Once it makes us feel the country as a Utopia just with the laughter. Golf ground with green leaves make us so playful with horses. Looking at the sun rise by sitting beside the Horton plains while smoking or eating peanuts is the best thing I like. Looking at the hill tops by staying at the moon plains is just like a heartiest meditation.', 'Kandy Lake,View point,Local market,Botanical garden,Ramboda waterfalls,Tea factory\r\n', 8),
(37, '03. Nuwaraeliya city tour', NULL, 'Early in the morning if you like you can go moon plains,Gregory lake park (water sport, horse riding) Victoria park,Nuwaraeliya Local market & fruit market visit', 8),
(38, '04. Nuwaraeliya to Ella', 'ELLA is very touristic with its own nature with mist and cold, Flowers blossom in the sunshine make the nature very beauty. It is very famous to do hiking and for beautiful accommodations and tasty food.\r\n', 'From Nanu oya to Ella by train (only if you like. if not possible can travel even by car)', 8),
(39, '05. Ella to Bentota', 'BENTOTA is an area with a nice beach view. Turtles in Bentota are very cute than we think. And the area surrounded with famous madu river is well famous for boat safaris. And we can see lots of cinnamon gardens while doing that relaxing safety boat safari. Jet Ski, banana boat rides, kite surfs, sea plane tours are actually amazing. Jeffery Bava the world-famous architecture\'s beautiful home and home garden make us mute for a while after going to that awesome place. And a main point to say is that the turtle conservation project takes an important place in the area', 'Rawana waterfall,Udawalawa national park Safari,Galle fort', 8),
(40, '06. Bentota city tour', NULL, 'Turtle conservation project,Madu river boat safari & Fish massage,Shopping at Bentota city \r\n', 8),
(41, '07. Bentota to Airport via Colombo ', 'COLOMBO is the main city in Sri Lanka and its crowdie city with lots of people and service suppliers. It belongs to western province of the country. It has become a main touristic point not because of its beauty but because of the services can obtain there.', 'Colombo city tour,Shopping at Colombo,Gangaramaya temple,Independence square,Galle face,Colombo fort,National museum,Outside visit of Old parliament', 8),
(42, '01. Airport to Anuradhapura', 'ANURADAPURA is a major city in Sri Lanka. It is the capital city of North Central Province, Sri Lanka and the capital of Anuradhapura District. Anuradhapura is one of the ancient capitals of Sri Lanka, famous for its well-preserved ruins of an ancient Sri Lankan civilization.', 'Pinnawala elephant orphanage,Yapahuva,Anuradhapura sacred city tour to see ruins,statues and sthupas', 9),
(43, '02. Anuradapura to Sigiriya ', 'SIGIRIYA is an historical city which has a deep historical value. It is situated in the north central province of Srilanka. It is not only a rock but also a fortress used to be protective from invaders. It was built by king Kashyapa. There’s a nice and an interesting story also which was written around that place. Once it was nominated as a world\'s heritage.\r\n', 'Ayurwedhic hospital,Sigiriya rock fortress 5th century or Pidurangala rock,Elephant ride', 9),
(44, '03. Sigiriya to Polonnaruwa', 'POLONNARUWA is an ancient kingdom. Seems to be the second kingdom in Sri Lanka. Once the sacred tooth relic was established there to be protecting from foreign invaders. Polonnaruwa is a big city with ancient ruins, statues and stupas. Polonnaruwa is the second capital in Sri Lanka (10- 12 centuries). \r\n', 'After the Polonnaruwa city tour you can make a Safari Minneriya park or Kaudulla park', 9),
(45, '04. Polonnaruwa to Kandy', 'KANDY is a cultural city and very famous as a main city in Sri Lanka. And belongs to the central province of Sri Lanka. And it can be known as a sacred city with the world famous lord Buddha’s sacred tooth relic. It can be also introduced as an ancient kingdom of Sri Lanka which shows the dignity of little country.', 'Dambulla cave temple,Nalanda Gedige,Mathale Hindhu Temple,Temple of Tooth Relic', 9),
(46, '05. Kandy to Nuwaraeliya', 'NUWARAELIYA is situated in the central province of Srilanka. It’s the coldest area in our country. With the hill tops covering by the mist it’s add a heaven beauty to this little country. Flowers in little plants make us blind for a moment. Water falls which re coming from the mountain tops make our minds relax for a while.  Tea plantations runs to the infinity make us so attractive to the area and to the little country. Once it makes us feel the country as a Utopia just with the laughter. Golf ground with green leaves make us so playful with horses. Looking at the sun rise by sitting beside the Horton plains while smoking or eating peanuts is the best thing I like. Looking at the hill tops by staying at the moon plains is just like a heartiest meditation.\r\n', 'Kandy Botanical garden or Udawaththa forest,Tea factory,Tea plantation,Water fall sight seen,Around Nuwareliya town and Horton Plains', 9),
(47, '06. Nuwaraeliya to Mirissa', 'Mirissa is a small town on the south coast of Sri Lanka, located in the Matara District of the Southern Province. It is approximately 150 kilometers south of Colombo and Mirissa beach and nightlife make it a popular tourist destination.', 'Rawana water fall,Udawalawa elephant orphanage if we have enough time,Morning whale watching,Habaraduuwa turtle conservation projects\r\n', 9),
(48, '07. Airport via Colombo', 'COLOMBO is the main city in Sri Lanka and its crowdie city with lots of people and service suppliers. It belongs to western province of the country. It has become a main touristic point not because of its beauty but because of the services can obtain there.', 'If you have a late departure we can do a city tour around Colombo,With Bere lake,Shopping,Gangaramaya temple,Old parliament (just outside visit) etc...', 9),
(49, '01. Airport to Sigiriya', 'SIGIRIYA is an historical city which has a deep historical value. It is situated in the north central province of Srilanka. It is not only a rock but also a fortress used to be protective from invaders. It was built by king Kashyapa. There’s a nice and an interesting story also which was written around that place. Once it was nominated as a world\'s heritage.', 'Pinnawala elephant orphanage,Evening climb Pidurangala rock to see beautiful sunset\r\n', 10),
(50, '02. Sigiriya to Polonnaruwa', 'POLONNARUWA is an ancient kingdom. Seems to be the second kingdom in Sri Lanka. Once the sacred tooth relic was established there to be protecting from foreign invaders. Polonnaruwa is a big city with ancient ruins, statues and stupas. Polonnaruwa is the second capital in Sri Lanka (10- 12 centuries). \r\n', 'Polonnaruwa old cultural city,Minneriya or Kaudulla National park Safari\r\n', 10),
(51, '03. Sigiriya to Kandy', 'KANDY is a cultural city and very famous as a main city in Sri Lanka. It belongs to the central province of Sri Lanka. And it can be known as a sacred city with the world famous lord Buddha’s sacred tooth relic. It can be also introduced as an ancient kingdom of Sri Lanka which shows the dignity of little country.', 'Sigiriya rock fortress,Dambulla cave temple,Nalanda gedige,Hindu temple Matale,Cultural dancing shows\r\n', 10),
(52, '04. Kandy to Nuwaraeliya', 'NUWARAELIYA is situated in the central province of Srilanka. It’s the coldest area in our country. With the hill tops covering by the mist it’s add a heaven beauty to this little country. Flowers in little plants make us blind for a moment. Water falls which re coming from the mountain tops make our minds relax for a while.  Tea plantations runs to the infinity make us so attractive to the area and to the little country. Once it makes us feel the country as a Utopia just with the laughter. Golf ground with green leaves make us so playful with horses. Looking at the sun rise by sitting beside the Horton plains while smoking or eating peanuts is the best thing I like. Looking at the hill tops by staying at the moon plains is just like a heartiest meditation.\r\n', 'The Temple of tooth relic puja ceremony at 8.30am,Kandy Lake,Royal Botanical garden,Ramboda falls,Tea factory', 10),
(53, '05. Nuwaraeliya to Ella', 'ELLA is very touristic with its own nature with mist and cold, Flowers blossom in the sunshine make the nature very beauty. It is very famous to do hiking and for beautiful accommodations and tasty food.', 'Local market & Fruit market visit,Colonel building,Gregory Lake Park,From Nanu oya to Ella by Train (The most beautiful train ride in Sri Lanka),Ella Nine arch bridge,Little Adam’s peak', 10),
(54, '06. Ella to Bentota ', 'BENTOTA is an area with a nice beach view. Turtles in Bentota are very cute than we think. And the area surrounded with famous madu river is well famous for boat safaris. And we can see lots of cinnamon gardens while doing that relaxing safety boat safari. Jet Ski, banana boat rides, kite surfs, sea plane tours are actually amazing. Jeffery Bava the world famous architecture\'s beautiful home and home garden make us mute for a while after going to that awesome place. And a main point to say is that the turtle conservation project takes an important place in the area.', 'Rawana waterfall,Buduruwagala temple,Udawalawa elephant orphanage,Galle fort', 10),
(55, '07. Bentota to Negombo', 'NEGOMBO is a popular destination for tourists with its pristine beaches, historic canals, lagoons and other breathtaking views. The Porutota stretch has been known for its mushrooming pubs and restaurants for quite a long time. Since many of the star class hotels are also found along this street local businesses too are having quite a potential with tourists walking in to them almost all the time. Shops selling souvenirs shops, swimming accessories, clothes are also found in addition to the pubs and cafes. In an attempt to find out some of the happening places in town, the Life Online walked in to a few known places to taste some of their signature dishes. We also didn’t forget to visit some of the iconic landmarks in town including the fish market, the lagoons and other sacred places of worship.', 'Madu river boat safari,Turtle conservation project', 10),
(56, '08. Negambo to Airport via Colombo', 'COLOMBO is the main city in Sri Lanka and its crowdie city with lots of people and service suppliers. It belongs to western province of the country. It has become a main touristic point not because of its beauty but because of the services can obtain there.', 'Shopping at Colombo,Gangaramaya temple,Independence square,Galle face,Colombo fort,National museum,Outside visit of Old parliament,Local markets ', 10);

--
-- Indexes for dumped tables
--

--
-- Indexes for table `hotel_ratings`
--
ALTER TABLE `hotel_ratings`
  ADD PRIMARY KEY (`id_hotel_ratings`);

--
-- Indexes for table `package`
--
ALTER TABLE `package`
  ADD PRIMARY KEY (`package_id`),
  ADD KEY `fk_package_tour_1` (`tour_id`);

--
-- Indexes for table `testimonial`
--
ALTER TABLE `testimonial`
  ADD PRIMARY KEY (`id_testimonial`);

--
-- Indexes for table `tour`
--
ALTER TABLE `tour`
  ADD PRIMARY KEY (`tour_id`);

--
-- Indexes for table `trip`
--
ALTER TABLE `trip`
  ADD PRIMARY KEY (`trip_id`),
  ADD KEY `fk_day_package_1` (`package_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `hotel_ratings`
--
ALTER TABLE `hotel_ratings`
  MODIFY `id_hotel_ratings` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=5;

--
-- AUTO_INCREMENT for table `package`
--
ALTER TABLE `package`
  MODIFY `package_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=11;

--
-- AUTO_INCREMENT for table `testimonial`
--
ALTER TABLE `testimonial`
  MODIFY `id_testimonial` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=56;

--
-- AUTO_INCREMENT for table `tour`
--
ALTER TABLE `tour`
  MODIFY `tour_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=7;

--
-- AUTO_INCREMENT for table `trip`
--
ALTER TABLE `trip`
  MODIFY `trip_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=57;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `package`
--
ALTER TABLE `package`
  ADD CONSTRAINT `fk_package_tour_1` FOREIGN KEY (`tour_id`) REFERENCES `tour` (`tour_id`) ON DELETE CASCADE ON UPDATE CASCADE;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
